### ISSUE TITLE
[2023/07/26] Retentive Network: A Successor to Transformer for Large Language Models

### ISSUE THREAD

**Issue by jonghwanhyeon** [zaemyung/Seeking-SOTA#102]
- Title: Retentive Network: A Successor to Transformer for Large Language Models
- Paper: [arXiv:2307.08621](https://arxiv.org/pdf/2307.08621)

> In this work, we propose Retentive Network (RetNet) as a foundation architecture for large language models, simultaneously achieving training parallelism, low-cost inference, and good performance. We theoretically derive the connection between recurrence and attention. Then we propose the retention mechanism for sequence modeling, which supports three computation paradigms, i.e., parallel, recurrent, and chunkwise recurrent. Specifically, the parallel representation allows for training parallelism. The recurrent representation enables low-cost O(1) inference, which improves decoding throughput, latency, and GPU memory without sacrificing performance. The chunkwise recurrent representation facilitates efficient long-sequence modeling with linear complexity, where each chunk is encoded parallelly while recurrently summarizing the chunks. Experimental results on language modeling show that RetNet achieves favorable scaling results, parallel training, low-cost deployment, and efficient inference. The intriguing properties make RetNet a strong successor to Transformer for large language models. Code will be available at https://aka.ms/retnet.

**Comment by jonghwanhyeon** [comment]
[Retentive Network - A Successor to Transformer for Large Language Models.pdf](https://github.com/zaemyung/Seeking-SOTA/files/12173613/Retentive.Network.-.A.Successor.to.Transformer.for.Large.Language.Models.pdf)

**Comment by zaemyung** [comment]
https://huggingface.co/papers/2307.08621
