### ISSUE TITLE
[2024/04/03] Effective gene expression prediction from sequence by integrating long-range interactions

### ISSUE THREAD

**Issue by namks** [zaemyung/Seeking-SOTA#134]
* Title: Effective gene expression prediction from sequence by integrating long-range interactions
* Authors: Žiga Avsec et al. (DeepMind)
* Publication: _Nature Methods_ (2021)
* Paper: https://www.nature.com/articles/s41592-021-01252-x
* Abstract:
> How noncoding DNA determines gene expression in different cell types is a major unsolved problem, and critical downstream applications in human genetics depend on improved solutions. Here, we report substantially improved gene expression prediction accuracy from DNA sequences through the use of a deep learning architecture, called Enformer, that is able to integrate information from long-range interactions (up to 100 kb away) in the genome. This improvement yielded more accurate variant effect predictions on gene expression for both natural genetic variants and saturation mutagenesis measured by massively parallel reporter assays. Furthermore, Enformer learned to predict enhancer–promoter interactions directly from the DNA sequence competitively with methods that take direct experimental data as input. We expect that these advances will enable more effective fine-mapping of human disease associations and provide a framework to interpret cis-regulatory evolution.

**Comment by namks** [comment]
[240403_Enformer.pdf](https://github.com/zaemyung/Seeking-SOTA/files/14853578/240403_Enformer.pdf)

**Comment by zaemyung** [comment]
Efficient Streaming Language Models with Attention Sinks
https://openreview.net/forum?id=NG7sS51zVF
