### ISSUE TITLE
[2020/12/02] The Convolution Exponential and Generalized Sylvester Flows

### ISSUE THREAD

**Issue by kwangheeya** [zaemyung/Seeking-SOTA#23]
- The Convolution Exponential and Generalized Sylvester Flows
- Neurips 2020
- https://papers.nips.cc/paper/2020/hash/d3f06eef2ffac7faadbe3055a70682ac-Abstract.html
- Code: https://github.com/ehoogeboom/convolution_exponential_and_sylvester
- Video on ICML ver.: https://slideslive.com/38930926

> This paper introduces a new method to build linear flows, by taking the exponential of a linear transformation. This linear transformation does not need to be invertible itself, and the exponential has the following desirable properties: it is guaranteed to be invertible, its inverse is straightforward to compute and the log Jacobian determinant is equal to the trace of the linear transformation. An important insight is that the exponential can be computed implicitly, which allows the use of convolutional layers. Using this insight, we develop new invertible transformations named convolution exponentials and graph convolution exponentials, which retain the equivariance of their underlying transformations. In addition, we generalize Sylvester Flows and propose Convolutional Sylvester Flows which are based on the generalization and the convolution exponential as basis change. Empirically, we show that the convolution exponential outperforms other linear transformations in generative flows on CIFAR10 and the graph convolution exponential improves the performance of graph normalizing flows. In addition, we show that Convolutional Sylvester Flows improve performance over residual flows as a generative flow model measured in log-likelihood.

**Comment by kwangheeya** [comment]
[1202_expo_cov.pdf](https://github.com/zaemyung/ml-study/files/5627824/1202_expo_cov.pdf)

**Comment by zaemyung** [comment]
일타강사 광희님의 행보가 기대됩니다~
