### ISSUE TITLE
[2020/10/16] Implicit Neural Representations with Periodic Activation Functions

### ISSUE THREAD

**Issue by kwangheeya** [zaemyung/Seeking-SOTA#3]
- Implicit Neural Representations with Periodic Activation Functions
- Neurips 2020
- https://arxiv.org/abs/2006.09661

> Implicitly defined, continuous, differentiable signal representations parameterized by neural networks have emerged as a powerful paradigm, offering many possible benefits over conventional representations. However, current network architectures for such implicit neural representations are incapable of modeling signals with fine detail, and fail to represent a signal's spatial and temporal derivatives, despite the fact that these are essential to many physical signals defined implicitly as the solution to partial differential equations. We propose to leverage periodic activation functions for implicit neural representations and demonstrate that these networks, dubbed sinusoidal representation networks or Sirens, are ideally suited for representing complex natural signals and their derivatives. We analyze Siren activation statistics to propose a principled initialization scheme and demonstrate the representation of images, wavefields, video, sound, and their derivatives. Further, we show how Sirens can be leveraged to solve challenging boundary value problems, such as particular Eikonal equations (yielding signed distance functions), the Poisson equation, and the Helmholtz and wave equations. Lastly, we combine Sirens with hypernetworks to learn priors over the space of Siren functions.

**Comment by kwangheeya** [comment]
시간: 한국시간 오후4시30분

**Comment by zaemyung** [comment]
- Spatial or spatio-temporal 데이터들을 디테일까지 잘 표현하려면 first-order, second-order 미분까지 잘 가능해야 하는데 그걸 사인형 함수를 써서 하는 것을 제안. 왜냐면, 사인을 미분하면 다시 shfited 된 사인이 나오기 때문에 적절하다.
  - 반면, 렐루의 경우 second-order 미분값이 0이기에 부적절.
- 다만 논문에서 제안한 initialization을 사용해야 함.
- 비전, 비디오, 물리 실험, 스피치 등 여러 가지 태스크에 대해 실험을 많이 진행함.

**Comment by zaemyung** [comment]
@lekwanghee 발표 때 만드셨던 슬라이드 링크 올려주시면 나중에 참고하기 좋을 것 같습니다 ^0^

**Comment by kwangheeya** [comment]
[1016_implicitNeuralRepresentation.pdf](https://github.com/zaemyung/ml-study/files/5427600/1016_implicitNeuralRepresentation.pdf)
