### ISSUE TITLE
[2022/08/31] Self-Attention Between Datapoints: Going Beyond Individual Input-Output Pairs in Deep Learning

### ISSUE THREAD

**Issue by zaemyung** [zaemyung/Seeking-SOTA#57]
[Self-Attention Between Datapoints: Going Beyond Individual Input-Output Pairs in Deep Learning](https://openreview.net/forum?id=wRXzOa2z5T)
- Jannik Kossen, Neil Band, Clare Lyle, Aidan Gomez, Tom Rainforth, Yarin Gal
- NeurIPS 2021
- [저자 동영상 발표](https://slideslive.com/38968090/selfattention-between-datapoints-going-beyond-individual-inputoutput-pairs-in-deep-learning?ref=speaker-17209)
- [논문 설명 비디오](https://www.youtube.com/watch?v=6ekOVosCQN8)
- [코드](https://github.com/OATML/non-parametric-transformers)
- (참고) [multi-head self-attention 설명 글](https://ratsgo.github.io/nlpbook/docs/language_model/tr_self_attention/)
> We challenge a common assumption underlying most supervised deep learning: that a model makes a prediction depending only on its parameters and the features of a single input. To this end, we introduce a general-purpose deep learning architecture that takes as input the entire dataset instead of processing one datapoint at a time. Our approach uses self-attention to reason about relationships between datapoints explicitly, which can be seen as realizing non-parametric models using parametric attention mechanisms. However, unlike conventional non-parametric models, we let the model learn end-to-end from the data how to make use of other datapoints for prediction. Empirically, our models solve cross-datapoint lookup and complex reasoning tasks unsolvable by traditional deep learning models. We show highly competitive results on tabular data, early results on CIFAR-10, and give insight into how the model makes use of the interactions between points.

**Comment by suinkim28** [comment]
최근에 tabular data 를 통한 regression task 를 많이 진행하고 있습니다. 

현업에서는 DNN 이 random forest 와 같은 ensemble models 보다 복잡한 것에 대비해 그만큼 더 좋은 성능을 못 보이는 것이 현실인데 흥미로운 모델인것 같습니다.

- missing data 가 있는 경우 data interpolation 에 사용될 수 있을지
    - 예를 들면 1년간의 데이터 중 특정 feature 는 최근 6개월밖에 없음
    - 혹은 interpolation 을 굳이 안하더라도 나머지 feature 를 통해 prediction 을 더 잘 할수 있을지
- 업의 특성상 데이터가 극단적으로 적은 경우가 있는데 기존 방식보다 더 좋은 성능을 보일지

등등이 궁금하고 조만간 실험을 한번 해보도록 하겠습니다.

**Comment by zaemyung** [comment]
@suinkim28 실험 결과가 기대됩니다! :D
