### ISSUE TITLE
[2022/11/09] Unsupervised Translation of Programming Languages

### ISSUE THREAD

**Issue by zaemyung** [zaemyung/Seeking-SOTA#67]
- 제목: Unsupervised Translation of Programming Languages
- 출판: NeurIPS 2020
- Paper: https://proceedings.neurips.cc/paper/2020/file/ed23fbf18c2cd35f8c7f8de44f85c08d-Paper.pdf
- Video: https://papertalk.org/papertalks/9347
> A transcompiler, also known as source-to-source translator, is a system that converts source code from a high-level programming language (such as C++ or Python) to another. Transcompilers are primarily used for interoperability, and to port codebases written in an obsolete or deprecated language (e.g. COBOL, Python 2) to a modern one. They typically rely on handcrafted rewrite rules, applied to the source code abstract syntax tree. Unfortunately, the resulting translations often lack readability, fail to respect the target language conventions, and require manual modifications in order to work properly. The overall translation process is time-consuming and requires expertise in both the source and target languages, making code-translation projects expensive. Although neural models significantly outperform their rule-based counterparts in the context of natural language translation, their applications to transcompilation have been limited due to the scarcity of parallel data in this domain. In this paper, we propose to leverage recent approaches in unsupervised machine translation to train a fully unsupervised neural transcompiler. We train our model on source code from open source GitHub projects, and show that it can translate functions between C++, Java, and Python with high accuracy. Our method relies exclusively on monolingual source code, requires no expertise in the source or target languages, and can easily be generalized to other programming languages. We also build and release a test set composed of 852 parallel functions, along with unit tests to check the correctness of translations. We show that our model outperforms rule-based commercial baselines by a significant margin.

**Comment by suinkim28** [comment]
Today's slides: 
[2022_11_09_unsupervised_translation_of_programming_languages.pdf](https://github.com/zaemyung/Seeking-SOTA/files/9971089/2022_11_09_unsupervised_translation_of_programming_languages.pdf)
