### ISSUE TITLE
[2023/01/04] Better SGD using Second-order Momentum

### ISSUE THREAD

**Issue by Minosota** [zaemyung/Seeking-SOTA#73]
제목: Better SGD using Second-order Momentum
출판: NeurIPS 2022
https://openreview.net/pdf?id=9PNsCQpg-Ak
Abstract:
We develop a new algorithm for non-convex stochastic optimization that finds an ε-critical point in the optimal O(ε^−3) stochastic gradient and Hessian-vector product computations. Our algorithm uses Hessian-vector products to “correct” a bias term in the momentum of SGD with momentum. This leads to better gradient estimates in a manner analogous to variance reduction methods. In contrast to prior work, we do not require excessively large batch sizes, and are able to provide an adaptive algorithm whose convergence rate automatically improves with decreasing variance in the gradient estimates. We validate our results on a variety of large-scale deep learning architectures and benchmarks tasks.

**Comment by zaemyung** [comment]
[ML_study_Better SGD using Second-order Momentum.pdf](https://github.com/zaemyung/Seeking-SOTA/files/10344751/ML_study_Better.SGD.using.Second-order.Momentum.pdf)
