### ISSUE TITLE
[2023/02/01] ZeRO-infinity: breaking the GPU memory wall for extreme scale deep learning

### ISSUE THREAD

**Issue by zaemyung** [zaemyung/Seeking-SOTA#77]
#### ZeRO-infinity: breaking the GPU memory wall for extreme scale deep learning
- Authors: Samyam Rajbhandari, Olatunji Ruwase, Jeff Rasley, Shaden Smith, Yuxiong He
- Publication venue: SC 21 (The International Conference for High Performance Computing, Networking, Storage, and Analysis)
- [arXiv](https://arxiv.org/abs/2104.07857), [ACM DL](https://dl.acm.org/doi/abs/10.1145/3458817.3476205)

**Comment by suinkim28** [comment]
[2023_02_01_ZeRO-Infinity.pdf](https://github.com/zaemyung/Seeking-SOTA/files/10557884/2023_02_01_ZeRO-Infinity.pdf)
