### ISSUE TITLE
[2020/10/23] RaPP: Novelty Detection with Reconstruction along Projection Pathway

### ISSUE THREAD

**Issue by hagg30** [zaemyung/Seeking-SOTA#8]
- Autoencoder-based novelty detection 
- ICLR 2020 (poster)
- https://openreview.net/pdf?id=HkgeGeBYDB
- https://deview.kr/data/deview/2019/presentation/[143]DEVIEW2019_MakinaRocks_%E1%84%80%E1%85%B5%E1%86%B7%E1%84%80%E1%85%B5%E1%84%92%E1%85%A7%E1%86%AB.pdf

**Comment by passing2961** [comment]
제가 이쪽 도메인을 잘 몰라서 논문 읽을 때 조금 도움을 얻은 좋은 블로그 링크 올릴게요~

- [https://research.sualab.com/introduction/review/2020/01/30/anomaly-detection-overview-1.html](https://research.sualab.com/introduction/review/2020/01/30/anomaly-detection-overview-1.html)

**Comment by hagg30** [comment]
## Novelty Detection


### RaPP
- a new novelty detection method by utilizing hidden activation values of an input and its autoencoder reconstruction, and provide aggregation functions for them to quantify novelty of the input.
- RAPP extends the reconstruction concept in the input space into the hidden spaces.
- RAPP improves autoencoder-based novelty detection methods in diverse datasets.

![image](https://user-images.githubusercontent.com/8827034/96861096-95782780-149e-11eb-8d4d-054124cdbc25.png)

### Methods
- Simple aggregation along pathway.
- Normalized aggregation along pathway.

1. Simple aggregation along pathway.

![image](https://user-images.githubusercontent.com/8827034/96861269-d2dcb500-149e-11eb-95a2-355a4993746e.png)
![image](https://user-images.githubusercontent.com/8827034/96861309-dec87700-149e-11eb-9e84-559787d94e44.png)
![image](https://user-images.githubusercontent.com/8827034/96861423-08819e00-149f-11eb-9939-6183a1c5d82b.png)

2. Normalized aggregation along pathway.
![image](https://user-images.githubusercontent.com/8827034/96861492-23541280-149f-11eb-9972-eba8c15a99c5.png)
![image](https://user-images.githubusercontent.com/8827034/96861652-58f8fb80-149f-11eb-88a8-5778e0659000.png)

*SVD recall
![image](https://user-images.githubusercontent.com/8827034/96861912-bbea9280-149f-11eb-9349-82b5e2152003.png)

*Mahalanobis Distance
![image](https://user-images.githubusercontent.com/8827034/96864326-310b9700-14a3-11eb-95ba-71166d67908a.png)
"Measuring how many standard deviations away P is from the mean of D."

### Result
*setups
- Multimodal Normality: A single class is chosen to be the novelty class and the remaining classes are assigned as the normal class. This setup is repeated to produce sub-datasets Published as a conference paper at ICLR 2020 with all possible novelty assignments. For instance, MNIST results in a set of datasets with 10 different novelty classes.
- Unimodal Normality: In contrast to the multimodal normality setup, we take one class for normality, and the others for novelty. For instance, MNIST results in a set of datasets with 10 different normal classes.

![image](https://user-images.githubusercontent.com/8827034/96867383-99f50e00-14a7-11eb-9a8c-4f7fce4153b1.png)


### Computational cost

![image](https://user-images.githubusercontent.com/8827034/96887463-94a3bd80-14bf-11eb-871a-6ff7c35395c7.png)

**Comment by zaemyung** [comment]
FYI, "A Unifying Review of Deep and Shallow Anomaly Detection"
- https://arxiv.org/abs/2009.11732
