### ISSUE TITLE
[2023/04/05] Predicting Multi-level Socioeconomic Indicators from Structural Urban Imagery

### ISSUE THREAD

**Issue by zaemyung** [zaemyung/Seeking-SOTA#85]
- Title : Predicting Multi-level Socioeconomic Indicators from Structural Urban Imagery
- Author : Tong Li et al.
- Publication : CIKM 2022
- https://dl.acm.org/doi/abs/10.1145/3511808.3557153
> Understanding economic development and designing government policies requires accurate and timely measurements of socioeconomic activities. In this paper, we show how to leverage city structural information and urban imagery like satellite images and street view images to accurately predict multi-level socioeconomic indicators. Our framework consists of four steps. First, we extract structural information from cities by transforming real-world street networks into city graphs (GeoStruct). Second, we design a contrastive learning-based model to refine urban image features by looking at geographic similarity between images, with images that are geographically close together having similar features (GeoCLR). Third, we propose using street segments as containers to adaptively fuse the features of multi-view urban images, including satellite images and street view images (GeoFuse). Finally, given the city graph with a street segment as a node and a neighborhood area as a subgraph, we jointly model street- and neighborhood-level socioeconomic indicator predictions as node and subgraph classification tasks. The novelty of our method is that we introduce city structure to organize multi-view urban images and model the relationships between socioeconomic indicators at different levels. We evaluate our framework on the basis of real-world datasets collected in multiple cities. Our proposed framework improves performance by over 10% when compared to state-of-the-art baselines in terms of prediction accuracy and recall.

**Comment by MinNamgung** [comment]
[cikm22.pdf](https://github.com/zaemyung/Seeking-SOTA/files/11160369/cikm22.pdf)
